# Please avoid using Ctrl-v, it will paste your clipboard and trigger many unwanted event

[keybindings.main_menu]
exit = "Ctrl-x" # ctrl-c is implemented by default

unselect_request = "Left"
expand_collection = "Right"

move_request_up = "Ctrl-Up"
move_request_down = "Ctrl-Down"

next_environment = "Ctrl-e"
display_env_editor = "Shift-e"
display_cookies = "Ctrl-c"
display_logs = "Ctrl-l"

[keybindings.generic]
display_help = "Ctrl-h" # Take care to not overlap other inputs, the help can be triggered from anywhere

# E.g. Collection name, request name, URL, Header, Query param, Basic Auth, Bearer Token, Request body
[keybindings.generic.text_input]
quit_without_saving = "Esc"
save_and_quit_single_line = "Enter"
save_and_quit_area = "Ctrl-x"

# Will simulate most of the emcas key bindings in the text areas (e.g. Request body)
mode = "emacs"

# Navigation in tables, popups, up and down in the collections list
[keybindings.generic.navigation]
move_cursor_up = "Up"
move_cursor_down = "Down"
move_cursor_left = "Left"
move_cursor_right = "Right"

# Avoids overlapping when in text input (e.g. selecting a collection while creating a new request)
# Might not happen when using the default config
alt_move_cursor_up = "Up"
alt_move_cursor_down = "Down"
alt_move_cursor_left = "Left"
alt_move_cursor_right = "Right"

go_back = "Esc"
select = "Enter"

# Collections list, query params, headers, cookies
[keybindings.generic.list_and_table_actions]
create_element = "Ctrl-n"
delete_element = "Ctrl-d"
edit_element = "Enter" # Edit query param, header, basic auth, bearer token
rename_element = "Ctrl-r" # Only used in the collections list (main menu)
toggle_element = "Ctrl-t" # Only used in tables (Query params, headers, cookies)
duplicate_element = "Shift-d"

[keybindings.request_selected]
param_next_tab = "Tab"

change_url = "Ctrl-u"
change_method = "Ctrl-m"
request_settings = "Ctrl-s"

next_view = "Ctrl-v"

send_request = "Space"
alt_send_request = "Ctrl-Enter"

export_request = "Shift-E"

[keybindings.request_selected.param_tabs]
change_auth_method = "Ctrl-a"
change_body_content_type = "Ctrl-b"
change_message_type = "Ctrl-m"

[keybindings.request_selected.result_tabs]
scroll_up = "Ctrl-Up"
scroll_down = "Ctrl-Down"
scroll_left = "Ctrl-Left"
scroll_right = "Ctrl-Right"

yank_response_part = "Ctrl-y" # Used to yank the current result tab (e.g. body, headers, cookies)

result_next_tab = "Shift-BackTab" # Will use param_next_tab depending on the selected view