# Please avoid using Ctrl-v, it will paste your clipboard and trigger many unwanted event

[keybindings.main_menu]
exit = "q" # ctrl-c is implemented by default

unselect_request = "Left"
expand_collection = "Right"

move_request_up = "Ctrl-Up"
move_request_down = "Ctrl-Down"

next_environment = "e"
display_cookies = "c"

[keybindings.generic]
display_help = "Ctrl-h" # Take care to not overlap other inputs, the help can be triggered from anywhere

# Collection name, request name, URL, Header, Query param, Basic Auth, Bearer Token
[keybindings.generic.text_inputs.text_input]
cancel = "Esc"
confirm = "Enter"

delete_backward = "Delete"
delete_forward = "Backspace"

move_cursor_left = "Left"
move_cursor_right = "Right"

validate = "Enter"

# Request body
[keybindings.generic.text_inputs.text_area_mode.Custom]
quit_without_saving = "Esc"
save_and_quit = "Ctrl-s"

copy = "Ctrl-c"
paste = "Ctrl-v"
undo = "Ctrl-z"
redo = "Ctrl-y"

new_line = "Enter"
indent = "Tab"
delete_backward = "Delete"
delete_forward = "Backspace"

skip_word_right = "Ctrl-Right"
skip_word_left = "Ctrl-Left"

move_cursor_up = "Up"
move_cursor_down = "Down"
move_cursor_left = "Left"
move_cursor_right = "Right"

# Navigation in tables, popups, up and down in the collections list
[keybindings.generic.navigation]
move_cursor_up = "Up"
move_cursor_down = "Down"
move_cursor_left = "Left"
move_cursor_right = "Right"

# Avoids overlapping when in text input (e.g. selecting a collection while creating a new request)
# Might not happen when using the default config
alt_move_cursor_up = "Up"
alt_move_cursor_down = "Down"
alt_move_cursor_left = "Left"
alt_move_cursor_right = "Right"

go_back = "Esc"
select = "Enter"

# Collections list, query params, headers, cookies
[keybindings.generic.list_and_table_actions]
create_element = "n"
delete_element = "d"
edit_element = "Enter" # Edit query param, header, basic auth, bearer token
rename_element = "r" # Only used in the collections list (main menu)
toggle_element = "t" # Only used in tables (Query params, headers, cookies)

[keybindings.request_selected]
param_next_tab = "Tab"

change_url = "u"
change_method = "m"
request_settings = "s"

next_view = "v"

send_request = "Space"
alt_send_request = "Ctrl-Enter"

[keybindings.request_selected.param_tabs]
change_auth_method = "Ctrl-a"
change_body_content_type = "Ctrl-b"

[keybindings.request_selected.result_tabs]
scroll_up = "Ctrl-Up"
scroll_down = "Ctrl-Down"
scroll_left = "Ctrl-Left"
scroll_right = "Ctrl-Right"

yank_response_part = "y" # Used to yank the current result tab (e.g. body, headers, cookies)

result_next_tab = "Shift-BackTab" # Will use param_next_tab depending on the selected view